spring:
  application:
    name: givebridge

  datasource:
    url: jdbc:postgresql://localhost:5432/givebridge
    username: givebridge_user
    password: givebridge_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080